### ISSUE TITLE
Multi-channel expected input format

### ISSUE THREAD

**Issue by akryeem** [BGU-CS-VIL/dtan#8]
Hi Ron,
Looking at your code, I see you have some checks for dealing with multichannel cases. However, I can't find any example or reference for the format you would expect for multichannel data.
Is multichannel data supported in your code, or I'm missing something?
If it is supported, in which format is it expected to be?

Thanks

**Comment by ronshapiraweber** [comment]
Hi Alaa, 
There were issues in the multichannel case, thank you for bringing it to my attention! 
I have pushed a fix, which should address the issue It was tested with the following UCR multivariate data:
```
StandWalkJump dataset details:
    X train.shape: (12, 4, 2500)
    X test.shape: (15, 4, 2500)
    y train.shape: (12,)
    y test.shape: (15,)
    number of classes: 3
    number of samples: 12
    number of channels:  4
    data sample dim: (4, 2500)
```
As you can see, we follow standard torch dims **(samples, channels, time-steps)**. 
Since UCR data usually comes in the following dims: (samples, timesteps, channels), we simply swap the 1 and 2 axes (see [tslearn doc](https://tslearn.readthedocs.io/en/stable/gettingstarted.html#time-series-format)). 

Fix includes: 
1. Add channel dim to locnet
2. fixed variance computation between channels at alignment_loss.py 

Note: current implementation supports the same warp for all channels which makes sense when channels are highly correlated. To get channel-dependent warps you should: 
1. Add per-channel fully-connected layer, where (dim=theta) 
2. adjust the prior accordingly. 

Please let me know if this resolves your issue. 
Feel free to contact me if you have any more questions. 

Ron

**Comment by akryeem** [comment]
Thanks for your efforts Ron, the latest version does support multichannel, I was able to run it and get results.
However, it doesn't support user given datasets (it only work with URC datasets), I create a PR to fix this. #9 
Please let me know if it looks ok to you.
